name = "Khakas"
version = "0.1.1"

[macos]
system_pkg_id = "no.divvun.MacDivvun.kjh"

[windows]
system_product_code = "0F8EC27D-3504-4407-882E-9E1C7E255CE0"
msoffice_product_code = "4F967AF7-857F-4ED9-A041-051449069F99"
