template = "https://github.com/giellalt/template-lang-und"
rev_id = 299
template_sha = "c2c940ccf19bf74ce9b697c688363766fc219a10"

[replacements]
__GLOTTOLOG_ID__ = "khak1248"
__REPO__ = "lang-kjh"
__UND2C__ = "kjh"
__UNDEFINED__ = "Khakas"
__UND__ = "kjh"
